<<<<<<< HEAD
theme: jekyll-theme-minimal
title: Octocat's homepage
description: this is to remember what i have learnt when !
=======
theme:jekyll-theme-minimal
title:Gaurav Srivastava | 1E9 Advisors
description:Day1 learning
>>>>>>> b7945558e9a1be31fb358d6f8798d2d864918a0d
